# Generated by Django 6.0.3 on 2026-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 'Terrible'), (2, 'Very Bad'), (3, 'Bad'), (4, 'Low'), (5, 'Neutral'), (6, 'Okay'), (7, 'Good'), (8, 'Great'), (9, 'Excellent'), (10, 'Amazing')])),
                ('note', models.TextField(blank=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
