# Generated by Django 6.0.3 on 2026-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('mindfulness', 'Mindfulness'), ('exercise', 'Exercise'), ('sleep', 'Sleep'), ('social', 'Social'), ('diet', 'Diet'), ('general', 'General')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
